# Product data extracted from pasxalis-query.csv
# Auto-generated - do not edit manually

PRODUCTS_CSV_DATA = """1,TEREA RUSSET,10,ΤΕΜΑΧΙΟ,KOYTA
2,TEREA AMBER,10,ΤΕΜΑΧΙΟ,KOYTA
3,TEREA YELLOW,10,ΤΕΜΑΧΙΟ,KOYTA
4,TEREA TURQUOISE,10,ΤΕΜΑΧΙΟ,KOYTA
5,TEREA SIENNA,10,ΤΕΜΑΧΙΟ,KOYTA
6,TEREA BRONZE,10,ΤΕΜΑΧΙΟ,KOYTA
7,TEREA SILVER,10,ΤΕΜΑΧΙΟ,KOYTA
8,TEREA TEAK,10,ΤΕΜΑΧΙΟ,KOYTA
9,TEREA WARM FUSE,10,ΤΕΜΑΧΙΟ,KOYTA
10,TEREA SOFT FUSE,10,ΤΕΜΑΧΙΟ,KOYTA
15,MARLBORO 100s,10,ΤΕΜΑΧΙΟ,KOYTA
16,MARLBORO GOLD 100s,10,ΤΕΜΑΧΙΟ,KOYTA
17,MARLBORO SILVER BLUE,10,ΤΕΜΑΧΙΟ,KOYTA
18,MARLBORO TOUCH,10,ΤΕΜΑΧΙΟ,KOYTA
21,MARLBORO RED 24s,8,ΤΕΜΑΧΙΟ,KOYTA
22,MARLBORO GOLD 24s,8,ΤΕΜΑΧΙΟ,KOYTA
23,MARLBORO CRAFTED RED,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
24,MARLBORO CRAFTED GOLD,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
26,MARLBORO CRAFTED GOLD 100s,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
27,MARLBORO SLIM BLUE 7MG,10,ΤΕΜΑΧΙΟ,KOYTA
30,ASSOS SLIM ΧΡΥΣΟ,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
31,ASSOS GOLDEN BOX 20s,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
32,ASSOS 24s RED,8,ΤΕΜΑΧΙΟ,KOYTA
33,ASSOS RED 20s BOX,10,ΤΕΜΑΧΙΟ,KOYTA
34,ASSOS BLUE 20s BOX,10,ΤΕΜΑΧΙΟ,KOYTA
38,PHILIP MORRIS SSLIM BLUE- No4 ΓΑΛΑΖΙΟ,10,ΤΕΜΑΧΙΟ,KOYTA
39,PHILIP MORRIS SSLIM PURPLE - VIOLET,10,ΤΕΜΑΧΙΟ,KOYTA
40,PHILIP MORRIS SSLIM PINK- No1 ΣΟΜΟΝ,10,ΤΕΜΑΧΙΟ,KOYTA
44,MURATTI,10,ΤΕΜΑΧΙΟ,KOYTA
47,L&M 100s RED,10,ΤΕΜΑΧΙΟ,KOYTA
48,L&M 100s BLUE,10,ΤΕΜΑΧΙΟ,KOYTA
49,VEEV ONE BLENDED TOBACCO 1,6%,5,ΤΕΜΑΧΙΟ,KOYTA
50,VEEV ONE BALANCED TOBACCO 1,6%,5,ΤΕΜΑΧΙΟ,KOYTA
51,VEEV ONE BLUE MINT 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
52,VEEV ONE BLUEBERRY 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
53,LIL EZ KIT (BLACK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
54,LIL EZ KIT (BLUE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
55,LIL EZ KIT (ROSE GOLD),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
56,IQOS KIT ILUMA ONE - PEBBLE GREY,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
57,IQOS KIT ILUMA ONE - PEBBLE BEIGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
58,IQOS KIT ILUMA ONE - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
59,IQOS KIT ILUMA ONE -  MOSS GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
60,IQOS KIT ILUMA ONE -  SUNSET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
63,IQOS KIT ILUMA - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
65,IQOS KIT ILUMA - SUNSET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
66,HOLDER IQOS ILUMA ONE - PEBBLE GREY,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
67,HOLDER IQOS ILUMA ONE - PEBBLE BEIGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
68,HOLDER IQOS ILUMA ONE - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
69,HOLDER IQOS ILUMA ONE - MOSS GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
70,HOLDER IQOS ILUMA ONE - SUNSET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
71,HOLDER IQOS ILUMA  - PEBBLE GREY,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
72,HOLDER IQOS ILUMA  - PEBBLE BEIGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
73,HOLDER IQOS ILUMA  - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
74,HOLDER IQOS ILUMA  - MOSS GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
75,HOLDER IQOS ILUMA  - SUNSET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
76,CHARGER IQOS ILUMA  - PEBBLE GREY,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
77,CHARGER IQOS ILUMA  - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
78,CHARGER IQOS ILUMA  - MOSS GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
79,CHARGER IQOS ILUMA  - SUNSET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
80,CHARGER IQOS ILUMA PRIME - JADE GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
82,IQOS VEEV ONE KIT (VELVET BLACK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
83,IQOS VEEV ONE KIT (ELECTRIC PURPLE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
84,IQOS 30 GLYCERIN CLEANING STICKS,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
85,CLEANER IQOS (3.0 PALE BLUE SLU),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
86,IQOS SILICONE SLEEVE (ILUMA - TINTED TEAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
87,IQOS FABRIC SLEEVE (ILUMA - DARK GREΥ),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
88,IQOS SILICONE SLEEVE (ILUMA ONE- NEW INDIGO),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
89,IQOS SILICONE SLEEVE (ILUMA ONE- CLARET RED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
90,IQOS SILICONE SLEEVE (ILUMA ONE- BRIGHT CORAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
91,IQOS SILICONE SLEEVE (ILUMA ONE- CHARTREUSE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
92,IQOS SILICONE SLEEVE (ILUMA ONE- TINTED TEAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
93,IQOS ALUMINUM DOOR (ILUMA - SUNSET RED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
94,IQOS DOOR (ILUMA - MATTE CORAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
95,IQOS DOOR (ILUMA - MOSS GREEN),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
96,IQOS DOOR (ILUMA - AZURE BLUE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
97,ΚΑΠΝΟΣ MARLBORO RYO RED 30gr,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
98,ΚΑΠΝΟΣ MARLBORO RYO GOLD 30gr,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
100,ΚΑΠΝΟΣ ASSOS ΚΑΦΕ 30gr,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
105,ΚΑΠΝΟΣ SKANDINAVIK REGULAR 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
106,ΚΑΠΝΟΣ SKANDINAVIK SUNGOLD (VANILLA) 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
108,ΚΑΠΝΟΣ BORKUM RIFF BRONZE (WHISKY) 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
113,ΚΑΠΝΟΣ DAVIDOFF BRAZIL 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
114,ΚΑΠΝΟΣ DAVIDOFF SCOTTISH MIXTURE 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
115,ΚΑΠΝΟΣ DAVIDOFF ARGENTINA 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
116,ΚΑΠΝΟΣ DAVIDOFF MALAWI 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
117,ΚΑΠΝΟΣ DAVIDOFF ENGLISH MIXTURE 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
118,ΚΑΠΝΟΣ DAVIDOFF FLAKE MEDALLIONS 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
121,ΠOYPA MARLBORO CRAFTED CIG/LOS 10s,20,ΤΕΜΑΧΙΟ,KOYTA
122,ΠΟΥΡΑ L&M CIG/LOS RED 10s,20,ΤΕΜΑΧΙΟ,KOYTA
123,ΠΟΥΡΑ L&M CIG/LOS BLUE 10s,20,ΤΕΜΑΧΙΟ,KOYTA
126,ΠOYPA SIGNATURE ORIGINAL TIN 20s ΚΙΤΡΙΝΟ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
128,ΠOYPA PARTAGAS CHICOS 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
129,ΠOYPA PARTAGAS CLUB 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
130,ΠOYPA COHIBA MINI 10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
131,ΠOYPA COHIBA CLUB 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
132,ΠOYPA GUANTANAMERA PURITOS 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
133,ΠΟΥΡΑ GUANTAΝΑMERA MINI 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
134,ΠOYPA MONTECRISTO MINI 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
135,ΠOYPA MONTECRISTO MINI 10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
136,ΠOYPA ROMEO & JULIETA CIG.10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
137,ΠOYPA ROMEO Y JULIETA CLUB 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
139,ΠOYPA TOSCANO TOSCANELLO,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
145,ΠOYPA LA PAZ MINI CIG/LOS 10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
148,ΠΟΥΡΑ MEHARIS JAVA 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
153,ΠΟΥΡΑ PANTER RED FILTER 14s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
154,ΠΟΥΡΑ PANTER DESERT FILTER 14s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
157,ΠOYPA VDG CIG/LOS CAPA DE ORO 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
171,ΤΣΙ/ΤΟ GIZEH EXTRA SLIM SUPER FINE 66s,50,ΤΕΜΑΧΙΟ,KOYTA
172,ΤΣΙ/ΤΟ GIZEH CUT CORNERS SUPER FINE 50s,50,ΤΕΜΑΧΙΟ,KOYTA
173,ΤΣΙ/ΤΟ GIZEH KING SIZE EXTRA  FINE SLIM 34s +TIPS(ΜΑΥΡΟ,26,ΤΕΜΑΧΙΟ,KOYTA
174,ΤΣΙΓ/ΤΟ GIZEH BLACK EXTRA FINE 50s,50,ΤΕΜΑΧΙΟ,KOYTA
175,ΤΣΙΓ/ΤΟ GIZEH BLACK KING SIZE EXTRA FINE ROLLS SLIM,20,ΤΕΜΑΧΙΟ,KOYTA
176,ΑΝΑΠΤΗΡΑΣ CRICKET MINI SIMPLICITY,25,ΤΕΜΑΧΙΟ,KOYTA
177,ΑΝΑΠΤΗΡΑΣ CRICKET MINI FLUO,25,ΤΕΜΑΧΙΟ,KOYTA
178,ΑΝΑΠΤΗΡΑΣ CRICKET MINI PASTEL,25,ΤΕΜΑΧΙΟ,KOYTA
180,ΑΝΑΠΤΗΡΑΣ CRICKET ECO MINI,25,ΤΕΜΑΧΙΟ,KOYTA
182,ΣΠΙΡΤΑ CRICKET,100,ΤΕΜΑΧΙΟ,KOYTA
183,ΦΙΛΤΡΟ ΤΣΙΓΑΡΟΥ SWAN EXTRA SLIM (ΚΙΤΡΙΝΟ),20,ΤΕΜΑΧΙΟ,KOYTA
185,ΦΙΛΤΡΟ  SWAN EXTRA SLIM MENTHOL,20,ΤΕΜΑΧΙΟ,KOYTA
186,ΦΙΛΤΡΟ SWAN EXTRA SLIM 54s,20,ΤΕΜΑΧΙΟ,KOYTA
187,ΦΙΛΤΡΑ DISCOVERY SMOOTH 5.7mm CHARCOAL,20,ΤΕΜΑΧΙΟ,KOYTA
189,ΤΣΙΓ/ΤΟ OCB SINGLE PREMIUM ΜΑΥΡΟ 50s,25,ΤΕΜΑΧΙΟ,KOYTA
190,ΤΣΙΓ/ΤΟ OCB SINGLE ULTIMATE ΜΠΛΕ 50s,25,ΤΕΜΑΧΙΟ,KOYTA
191,ΤΣΙΓ/ΤΟ  OCB  SINGLE X-PERT SILVER 60s,25,ΤΕΜΑΧΙΟ,KOYTA
192,ΤΣΙΓ/ΤΟ  OCB  PREMIUM (ΜΑΥΡΟ) + TIPS 24/32,32,ΤΕΜΑΧΙΟ,KOYTA
193,ΤΣΙΓ/ΤΟ  OCB  ULTIMATE (ΜΠΛΕ) + TIPS 24/32,32,ΤΕΜΑΧΙΟ,KOYTA
194,ΤΣΙΓ/ΤΟ  OCB  VIRGIN (ΚΑΦΕ)+ TIPS 24/32,4,ΤΕΜΑΧΙΟ,ΠΑΚΕΤΟ 4
195,ΤΣΙΓ/ΤΟ  OCB  ORGANIC (ΜΠΕΖ) + TIPS 24/32,4,ΤΕΜΑΧΙΟ,ΠΑΚΕΤΟ 4
197,ΤΣΙΓ/ΤΟ  OCB  PREMIUM SLIM (ΜΕΓΑΛΟ),50,ΤΕΜΑΧΙΟ,KOYTA
198,ΤΣΙΓ/ΤΟ ROLLS OCB MINI,24,ΤΕΜΑΧΙΟ,KOYTA
199,ΤΣΙΓ/ΤΟ ROLLS OCB SLIM,24,ΤΕΜΑΧΙΟ,KOYTA
200,ΤΣΙΓ/ΤΟ  OCB  PREMIUM TIPS (ΤΖΙΒΑΝΑ),25,ΤΕΜΑΧΙΟ,KOYTA
201,SET ΑΝΑΠΤΗΡΕΣ CRICKET 75 ΤΕΜΑΧΙΑ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
202,VEEV ONE SEA MINT 1,6%,5,ΤΕΜΑΧΙΟ,KOYTA
203,VEEV ONE RED 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
204,VEEV ONE MANGO 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
205,VEEV ONE MELON COCONUT 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
206,VEEV ONE WATERMELON 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
207,VEEV ONE STRAWBERRY 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
208,ΠOYPA MONTECRISTO CLUB 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
209,ΠOYPA ROMEO & JULIETA PURITOS 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
210,IQOS VEEV ONE KIT (SILKY GREY),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
211,IQOS VEEV ONE KIT (LUCID GREEN),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
212,CHARGER IQOS ILUMA  - PEBBLE BEIGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
213,LEVIA ELECTRO ROUGE,10,ΤΕΜΑΧΙΟ,KOYTA
214,LEVIA ISLAND BEAT,10,ΤΕΜΑΧΙΟ,KOYTA
215,TEREA KONA,10,ΤΕΜΑΧΙΟ,KOYTA
216,TEREA DORE,10,ΤΕΜΑΧΙΟ,KOYTA
217,ΠΟΥΡΑ BREAK SILVER FILTER 17s,10,ΤΕΜΑΧΙΟ,KOYTA
220,ΠΟΥΡΑ PANTER RED FILTER 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
221,ZYN COOL MINT mini MEDIUM 3mg (8g),1,CAN,CAN
222,ZYN COOL MINT Mini STRONG 6mg (8g),1,CAN,CAN
223,ZYN ESPRESSINO Mini MEDIUM 3mg (8g),1,CAN,CAN
224,ZYN ESPRESSINO Mini STRONG 6mg (8g),1,CAN,CAN
225,ZYN ICY BLACKCURRANT Slim X-STRONG 11mg (14g),1,CAN,CAN
226,ZYN SPEARMINT Slim MEDIUM 6,5mg (14g),1,CAN,CAN
227,MARLBORO RED 29s,8,ΤΕΜΑΧΙΟ,KOYTA
228,MARLBORO GOLD 29s,8,ΤΕΜΑΧΙΟ,KOYTA
229,ΠΟΥΡΑ PANTER DESERT FILTER 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
230,ZYN COOL MINT Slim 9mg (14g),1,CAN,CAN
231,FIIT REGULAR 20s,10,ΤΕΜΑΧΙΟ,KOYTA
232,FIIT MARINE 20s,10,ΤΕΜΑΧΙΟ,KOYTA
233,FIIT REGULAR DEEP 20s,10,ΤΕΜΑΧΙΟ,KOYTA
235,FIIT ELEMENT FALL 20s,10,ΤΕΜΑΧΙΟ,KOYTA
237,FIIT REGULAR STONE 20s,10,ΤΕΜΑΧΙΟ,KOYTA
238,FIIT REGULAR COPPER 20s,10,ΤΕΜΑΧΙΟ,KOYTA
240,IQOS  ILUMA KIT i  PRIME - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
241,IQOS  ILUMA KIT i  PRIME - ASPEN GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
242,IQOS  ILUMA KIT i  PRIME - GARNET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
243,LEVIA GLACIAL BEAT,10,ΤΕΜΑΧΙΟ,KOYTA
244,IQOS VEEV ONE STARTER KIT BLACK (CL.TOBACCO),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
245,IQOS VEEV ONE STARTER KIT BLACK (BLUE MINT),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
247,VEEV ONE FLAVOR MIX,5,ΤΕΜΑΧΙΟ,KOYTA
250,ΠOYPA NOBEL PETIT ΚΙΤΡΙΝΟ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
253,ΠΟΥΡΑ ADORNADO CHURCHILL 10s,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
254,ΠΟΥΡΑ ADORNADO ROBUSTO 10s,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
258,LIL STYLERDECO PERSONALIZE (SOLID 2.0 ROSE GOLD),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
259,LIL USB CABLE (WHITE TYPE C),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
260,LIL POWER ADAPTOR (SOLID 2.0 WHITE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
261,LIL EZ DUAL CLEANER PRO,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
262,HOLDER IQOS ILUMA PRIME - OBSIDIAN BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
263,HOLDER IQOS ILUMA PRIME - GOLDEN KHAKI,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
264,HOLDER IQOS ILUMA PRIME - BRONZE TAUPE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
265,CHARGER IQOS ILUMA PRIME - OBSIDIAN BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
266,CHARGER IQOS ILUMA PRIME - GOLDEN KHAKI,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
267,CHARGER IQOS ILUMA PRIME - BRONZE TAUPE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
268,IQOS CAR TRAY (WITH PACK HOLDER) BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
271,IQOS CHARGING DOCK (ILUMA - CREAM,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
273,IQOS TRAY PINK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
274,UNBRANDED USB CABLE (CREAM),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
275,UNBRANDED POWER ADAPTOR TYPE C (CREAM),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
276,IQOS RING SET ( ILUMA - GROUNDED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
277,IQOS RING SET ( ILUMA - SOPHISTICATED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
278,IQOS RING SET ( ILUMA - ENERGIZED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
279,IQOS RING SET ( ILUMA - CELABRATE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
280,IQOS RING SET ( ILUMA - EXHILARATE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
281,IQOS SILICONE SLEEVE (ILUMA PRIME CITRON YELLOW),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
282,IQOS SILICONE SLEEVE (ILUMA PRIME BRIGHT CORAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
283,IQOS SILICONE SLEEVE (ILUMA PRIME LAKE BLUE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
284,IQOS SILICONE SLEEVE (ILUMA PRIME OBSIDIAN BLACK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
285,IQOS SILICONE SLEEVE (ILUMA - CHARTREUSE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
286,IQOS SILICONE SLEEVE (ILUMA - NEW INDIGO),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
287,IQOS SILICONE SLEEVE (ILUMA - CLARET RED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
288,IQOS SILICONE SLEEVE (ILUMA - BRIGHT CORAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
289,IQOS FABRIC SLEEVE (ILUMA - KHAKI),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
290,IQOS FABRIC SLEEVE (ILUMA - DARK GRΕEN),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
291,IQOS SILICONE SLEEVE (ILUMA ONE-CITRON YELLOW),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
292,IQOS FABRIC SLEEVE (ILUMA ONE- KHAKI),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
293,IQOS FABRIC SLEEVE (ILUMA ONE- DARK GREEN),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
294,IQOS FABRIC SLEEVE (ILUMA ONE- DARK GREY),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
295,IQOS SLEEVE (ILUMA ONE-KOLOR SILVER),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
296,IQOS  WRAP (ILUMA PRIME - KOLOR CORAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
297,IQOS  WRAP (ILUMA PRIME - KOLOR BLACK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
298,IQOS  WRAP (ILUMA PRIME - KOLOR SILVER),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
299,IQOS ΚΑΛΥΜΜΑ ΔΕΡΜΑΤΙΝΟ (ILUMA PRIME - GOLDEN KHAKI),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
300,IQOS ΚΑΛΥΜΜΑ ΥΦΑΣΜΑΤΙΝΟ (ILUMA PRIME - BRONZE TAUPE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
301,IQOS ΚΑΛΥΜΜΑ ΥΦΑΣΜΑΤΙΝΟ (ILUMA PRIME - JADE GREEN),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
302,IQOS ΚΑΛΥΜΜΑ ΥΦΑΣΜΑΤΙΝΟ (ILUMA PRIME - INDIGO),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
303,IQOS ΚΑΛΥΜΜΑ ΥΦΑΣΜΑΤΙΝΟ (ILUMA PRIME - WARM RED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
304,IQOS ΚΑΛΥΜΜΑ MICROFIBER (ILUMA PRIME - PALE PINK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
305,IQOS ΚΑΛΥΜΜΑ MICROFIBER (ILUMA PRIME - SAGE GREEN),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
306,IQOS ΚΑΛΥΜΜΑ MICROFIBER (ILUMA PRIME - SOFT TEAL),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
307,IQOS ΚΑΛΥΜΜΑ MICROFIBER (ILUMA PRIME - WARM YELLOW),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
308,IQOS ΚΑΛΥΜΜΑ ΙΡΙΔΙΖΟΝ (ILUMA PRIME - NIGHT SHADE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
309,IQOS ALUMINUM DOOR (ILUMA - PEBBLE BEIGE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
310,IQOS ALUMINUM DOOR (ILUMA - MOSS GREEN),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
311,IQOS ALUMINUM DOOR (ILUMA - PEBBLE GREY),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
312,IQOS IRI DOOR (ILUMA - ORANGE GLOW),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
314,IQOS DOOR (ILUMA - MATTE YELLOW),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
315,IQOS DOOR (ILUMA - MATTE LIME),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
316,IQOS DOOR (ILUMA - PEBBLE BEIGE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
317,IQOS DOOR (ILUMA - SUNSET RED),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
318,IQOS DOOR (ILUMA - PEBBLE GREY),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
319,HOLDER IQOS ILUMA i  PRIME - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
320,HOLDER IQOS ILUMA i  PRIME - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
321,HOLDER IQOS ILUMA i  PRIME - ASPEN GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
322,HOLDER IQOS ILUMA i  PRIME - GARNET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
323,CHARGER IQOS ILUMA i  PRIME - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
324,IQOS RING SET ( ILUMA - EMANATE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
325,MARLBORO TITANIUM RED 20s,10,ΤΕΜΑΧΙΟ,KOYTA
326,MARLBORO TITANIUM GOLD 20s,10,ΤΕΜΑΧΙΟ,KOYTA
327,VEEV NOW ULTRA BLUE RASPBERRY 1.8%,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
328,VEEV NOW ULTRA GRAPE 1.8%,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
329,VEEV NOW ULTRA STRAWBERRY 1.8%,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
330,VEEV NOW ULTRA GOLD TOBACCO 1,8%,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
331,VEEV NOW ULTRA CLASSIC MINT 1.8%,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
332,SET CRICKET FUSSION/B&G/PASTEL,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
334,ΠΟΥΡΑ MONTECRISTO 10s CLUB,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
335,MARLBORO (CELO L&M RED) CRAFTED RED 100s,10,ΤΕΜΑΧΙΟ,KOYTA
336,TEREA BEIGE,10,ΤΕΜΑΧΙΟ,KOYTA
337,ΠΟΥΡΑ TOSCANO ROBUSTO 4's (29,00) T&T,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
338,ΠΟΥΡΑ TOSCANO ROBUSTO 4's,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
339,IQOS ILUMA KIT i ONE - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
340,IQOS ILUMA KIT i ONE - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
341,IQOS VEEV ONE KIT - SE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
342,IQOS ILUMA KIT i ONE - LEAF GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
343,IQOS ILUMA KIT i ONE - DIGITAL VIOLET,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
344,IQOS VEEV ONE KIT - SE GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
345,IQOS ILUMA KIT i ONE - VIVID TERRACOTTA,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
346,IQOS ILUMA KIT i MID - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
347,IQOS ILUMA KIT i MID - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
348,IQOS ILUMA KIT i MID - VIVID TERRACOTTA,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
350,IQOS ILUMA KIT I MID - LEAF GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
351,HOLDER ILUMA i  - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
352,HOLDER ILUMA i - VIVID TERRACOTA,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
353,HOLDER ILUMA i-LEAF GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
354,HOLDER ILUMA i  - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
355,HOLDER ILUMA i-DIGITAL VIOLET,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
356,CHARGER ILUMA i-MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
357,CHARGER ILUMA i - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
358,CHARGER ILUMA i - VIVID TERRACOTTA,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
359,CHARGER ILUMA iLEAF GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
360,CHARGER ILUMA i-DIGITAL VIOLET,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
361,ΠΟΥΡΑ ROMEO & JULIETA No2 A/T 3CP,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
362,MARLBORO POCKETS GOLD,10,ΤΕΜΑΧΙΟ,KOYTA
363,ΠOYPA NOBEL PETIT ΚΙΤΡΙΝΟ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
366,MARLBORO POCKETS RED,10,ΤΕΜΑΧΙΟ,KOYTA
367,MARLBORO RED ΣKΛHPO,10,ΤΕΜΑΧΙΟ,KOYTA
368,MARLBORO RED MAΛAKO,10,ΤΕΜΑΧΙΟ,KOYTA
369,MARLBORO GOLD ΣKΛHPO,10,ΤΕΜΑΧΙΟ,KOYTA
370,MARLBORO GOLD MAΛAKΟ,10,ΤΕΜΑΧΙΟ,KOYTA
371,MARLBORO CRAFTED RED 100s,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
372,MARLBORO XSLIM GOLD S-LINE,10,ΤΕΜΑΧΙΟ,KOYTA
373,ASSOS SLIM ΜΩΒ,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
374,ASSOS RED 100s,10,ΤΕΜΑΧΙΟ,KOYTA
375,ASSOS BLUE 100s,10,ΤΕΜΑΧΙΟ,KOYTA
376,ASSOS ΦIΛTPO MAΛAKO,10,ΤΕΜΑΧΙΟ,KOYTA
377,PHILIP MORRIS 20s BLUE,10,ΤΕΜΑΧΙΟ,KOYTA
378,PHILIP MORRIS 20s WHITE - SILVER,10,ΤΕΜΑΧΙΟ,KOYTA
379,PHILIP MORRIS BLUE 100s,10,ΤΕΜΑΧΙΟ,KOYTA
380,FIIT REGULAR SKY 20s,10,ΤΕΜΑΧΙΟ,KOYTA
381,FIIT ELEMENT CAY 20s,10,ΤΕΜΑΧΙΟ,KOYTA
382,L&M 23s ΚΟΚΚΙΝΟ,8,ΤΕΜΑΧΙΟ,KOYTA
383,L&M 23s  ΜΠΛΕ,8,ΤΕΜΑΧΙΟ,KOYTA
384,LIL STYLERDECO PERSONALIZE (SOLID 2.0 COSMIC BLUE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
385,ΚΑΠΝΟΣ MARLBORO TOUCH 30gr,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
386,IQOS KIT ILUMA - PEBBLE GREY,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
387,IQOS KIT ILUMA - PEBBLE BEIGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
388,IQOS KIT ILUMA - MOSS GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
389,IQOS CERAMIC TRAY BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
390,IQOS TRAY ROYAL BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
391,IQOS IRI DOOR (ILUMA - PURPLE PLUME),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
392,IQOS VEEV ONE KIT (LUSCIOUS PINK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
393,VEEV ONE CLASSIC TOBACCO 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
394,VEEV ONE GRAPE 1,8%,5,ΤΕΜΑΧΙΟ,KOYTA
395,IQOS  ILUMA KIT i  PRIME - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
396,ΚΑΠΝΟΣ CLAN 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
397,ΚΑΠΝΟΣ SKANDINAVIK NAVY (AROMATIC) 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
398,ΚΑΠΝΟΣ SKANDINAVIK MIXTURE 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
399,ΚΑΠΝΟΣ SKANDINAVIK WHITE 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
400,ΠOYPA SIGNATURE MINI ORIGINAL 10s,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
401,ΠOYPA SIGNATURE MINI BLUE,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
402,ΠOYPA SIGNATURE TIN 20s BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
403,ΠOYPA NOBEL PETIT ΠΡΑΣΙΝΟ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
404,ΠOYPA NOBEL PETIT ΛΕΥΚΟ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
405,ΠΟΥΡΑ DAVIDOFF MINI GOLD 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
406,ΠΟΥΡΑ DAVIDOFF MINI SILVER 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
407,ΦΙΛΤΡΑ GIZEH POP-UP EXTRA SLIM 126s (ΛΕΥΚΟ),20,ΤΕΜΑΧΙΟ,KOYTA
408,ΠOYPA TOSCANO CLASSICO,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
409,ΠΟΥΡΑ TOSCANELLO ROSSO (KOKKINO) CAFFE,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
410,ΠΟΥΡΑ TOSCANO NERO (MAYPO) CIOCCOLATO,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
411,ΠΟΥΡΑ TOSCANELLO ROSSO ORO 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
412,ΠΟΥΡΑ TOSCANELLO CASTANO RAFFINATO 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
413,ΑΝΑΠΤΗΡΑΣ CRICKET MINI NAVY,25,ΤΕΜΑΧΙΟ,KOYTA
414,ΑΝΑΠΤΗΡΑΣ CRICKET ORIGINAL SIMPLICITY,25,ΤΕΜΑΧΙΟ,KOYTA
415,ΚΑΠΝΟΣ BORKUM RIFF RUBY 40gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
416,ΚΑΠΝΟΣ BORKUM RIFF SPECIAL MIXTURE No8,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
417,ΚΑΠΝΟΣ CAPTAIN BLACK GOLD 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
418,ΚΑΠΝΟΣ CAPTAIN BLACK REGULAR (ΛΕΥΚΟ) 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
419,ΚΑΠΝΟΣ CAPTAIN BLACK ROYAL 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
420,ΚΑΠΝΟΣ ERINMORE MIXTURE 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
421,ΚΑΠΝΟΣ ERINMORE FLAKE 50gr,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
422,ΦΙΛΤΡΟ ΤΣΙΓΑΡΟΥ SWAN SLIM (ΚΟΚΚΙΝΟ),20,ΤΕΜΑΧΙΟ,KOYTA
423,ΦΙΛΤΡΟ SWAN EXTRA SLIM 54s COMIC,20,ΤΕΜΑΧΙΟ,KOYTA
424,ΦΙΛΤΡΑ DISCOVERY LONG 5,7mm 150s,10,ΤΕΜΑΧΙΟ,KOYTA
425,ΠOYPA LA PAZ CIGARROS 5s,5,ΤΕΜΑΧΙΟ,KOYTA
426,ΠOYPA LA PAZ CIGARILLOS 10s,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
427,ΠΟΥΡΑ MEHARIS GOLD FILTER 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
428,ΠΟΥΡΑ MEHARIS ECUADOR 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
429,ΠΟΥΡΑ MEHARIS BRASIL 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
430,ΠΟΥΡΑ MEHARIS RED ORIENT 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
431,ΠΟΥΡΑ MEHARIS RED ORIENT FILTER 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
432,ΠΟΥΡΑ PANTER BLUE20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
433,ΠΟΥΡΑ PANTER DESSERT 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
434,ΠOYPA VDG CORONA CAPA DE ORO 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
435,ΠΟΥΡΑ HANDELSGOLD BLONDE 5s,10,ΤΕΜΑΧΙΟ,KOYTA
436,ΠΟΥΡΑ HANDELSGOLD RED (CHERRY) 5s,10,ΤΕΜΑΧΙΟ,KOYTA
437,ΠΟΥΡΑ HANDELSGOLD CLASSIC 5s,10,ΤΕΜΑΧΙΟ,KOYTA
438,ΠΟΥΡΑ HANDELSGOLD SUN (PEACH) 5s,10,ΤΕΜΑΧΙΟ,KOYTA
439,ΠΟΥΡΑ HANDELSGOLD BLUE (CHOCO) 5s,10,ΤΕΜΑΧΙΟ,KOYTA
440,ΠΟΥΡΑ HANDELSGOLD GREEN (APPLE) 5s,10,ΤΕΜΑΧΙΟ,KOYTA
441,ΠΟΥΡΑ HANDELSGOLD BROWN (COFFEE) 5s,10,ΤΕΜΑΧΙΟ,KOYTA
442,ΠΟΥΡΑ HANDELSGOLD WHITE (COCONUT) 5s,10,ΤΕΜΑΧΙΟ,KOYTA
443,ΠΟΥΡΑ HANDELSGOLD PURPLE 5s (2,00) Τ&Τ,10,ΤΕΜΑΧΙΟ,KOYTA
444,ΠOYPA CLUBMASTER MΙNI RED 20s,5,ΤΕΜΑΧΙΟ,KOYTA
445,ΠΟΥΡΑ CLUBMASTER MINI FILTER RED 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
446,ΠΟΥΡΑ CLUBMASTER SUPERIOR FILTER 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
447,ΠΟΥΡΑ CHAZZ CIGARILLOS 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
448,ΠΟΥΡΑ CHAZZ CIGARROS 10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
449,IQOS ILUMA KIT I MID-DIGITAL VIOLET,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
450,IQOS CERAMIC TRAY PUTTY,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
451,ΤΣΙΓ/ΤΟ  OCB  BAMBOO + TIPS 24/32,4,ΤΕΜΑΧΙΟ,ΠΑΚΕΤΟ 4
452,VEEV ONE WATERMELON 1,8% (1 POD),6,ΤΕΜΑΧΙΟ,KOYTA
453,VEEV ONE SEA MINT 1,6% (1POD),6,ΤΕΜΑΧΙΟ,KOYTA
454,VEEV ONE STRAWBERRY 1,8% (1 POD),6,ΤΕΜΑΧΙΟ,KOYTA
455,VEEV ONE CHERRY 1,8% (1POD),6,ΤΕΜΑΧΙΟ,KOYTA
456,VEEV ONE BLUEBERRY 1,8% (1 POD),6,ΤΕΜΑΧΙΟ,KOYTA
457,VEEV ONE  MANGO 1,8% (1POD),6,ΤΕΜΑΧΙΟ,KOYTA
458,VEEV ONE  MELLON COCONUT 1,8% (1POD),6,ΤΕΜΑΧΙΟ,KOYTA
459,VEEV ONE CLASSIC TOBACCO 1,8% (1 POD),6,ΤΕΜΑΧΙΟ,KOYTA
460,VEEV ONE GRAPE 1,8% (1 POD),6,ΤΕΜΑΧΙΟ,KOYTA
461,VEEV ONE SOUR APPLE 1,8% (1 POD),6,ΤΕΜΑΧΙΟ,KOYTA
462,VEEV ONE BLUE MINT 1,8% (1POD),6,ΤΕΜΑΧΙΟ,KOYTA
463,ΠOYPA VDG CIG/LOS CAPA DE ORO 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
464,IQOS KIT ILUMA - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
465,MARLBORO GOLD 100s,10,ΤΕΜΑΧΙΟ,KOYTA
466,ΠOYPA TOSCANO TOSCANELLO,5,ΤΕΜΑΧΙΟ,ΠΕΝΤΑΔΑ
467,ZYN COOL MINT mini X-Low 1.5mg,1,CAN,CAN
468,ZYN COFFE mini 3mg,1,CAN,CAN
469,ZYN COFFEE mini 6mg,1,CAN,CAN
470,ZYN COOL MINT mini 3mg,1,CAN,CAN
471,ZYN SPEARMINT mini X-Low 1.5mg,1,CAN,CAN
472,ZYN COOL MINT mini 6mg,1,CAN,CAN
473,ZYN SPEARMINT mini 3mg,1,CAN,CAN
474,ZYN COOL MINT Slim 11mg,1,CAN,CAN
475,MARLBORO 100s,10,ΤΕΜΑΧΙΟ,KOYTA
476,MARLBORO TOUCH,10,ΤΕΜΑΧΙΟ,KOYTA
477,ZYN COOL MINT Slim 9mg.,1,CAN,CAN
478,ZYN SPEARMINT mini 6mg,1,CAN,CAN
479,LEVIA PURPLE,10,ΤΕΜΑΧΙΟ,KOYTA
480,IQOS  ILUMA KIT i  PRIME - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
481,IQOS  ILUMA KIT i  PRIME - ASPEN GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
482,VEEV NOW ULTRA WATERMELON - Limited Edition 1.8%,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
483,VEEV NOW ULTRA MANGO - Limited Edition 1.8%,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
484,ΠOYPA PARTAGAS CLUB 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
485,ΠOYPA COHIBA CLUB 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
486,ΠΟΥΡΑ MONTECRISTO PURITOS 5s (8,70),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
487,ΠOYPA GUANTANAMERA CRISTALES TUBOS 5s (16,15) Τ&Τ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
488,IQOS VEEV ONE STARTER KIT BLACK (CL.TOBACCO),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
489,IQOS VEEV ONE STARTER KIT BLACK (BLUE MINT),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
490,ΠOYPA SIGNATURE MINI BEIGE 10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
491,ΠOYPA CAPTAIN BLACK CIG/LOS BEIGE 10s (3,30),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
492,ΠΟΥΡΑ REPOSADO CONNECTICUT ROBUSTO 10s (33.00) Τ&Τ,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
493,ΠΟΥΡΑ REPOSADO CONNECTICUT TORO10s (37,00),1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
494,TEREA BEIGE,10,ΤΕΜΑΧΙΟ,KOYTA
495,ΠΟΥΡΑ PARTAGAS SERIE (ΜΑΥΡΟ) MINI 20s (17,55),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
496,ΠOYPA JOSE PIEDRA CIGARILLOS 20s (14,20),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
497,IQOS ILUMA KIT i ONE - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
498,IQOS BAGS (RECYCLABLE) LARGE,50,ΤΕΜΑΧΙΟ,ΚΙΒΩΤΙΟ
499,IQOS BAGS (RECYCLABLE) MEDIUM,120,ΤΕΜΑΧΙΟ,ΚΙΒΩΤΙΟ
500,IQOS BAGS (RECYCLABLE) SMALL,120,ΤΕΜΑΧΙΟ,ΚΙΒΩΤΙΟ
501,ΠOYPA SIGNATURE 10s  BEIGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
502,IQOS CAR TRAY (WITH PACK HOLDER) BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
503,ΠOYPA VDG CORONA SUMATRA  5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
504,HOLDER IQOS ILUMA  - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
505,ΚΑΠΝΟΣ AMPHORA FULL AROMA,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
506,ΚΑΠΝΟΣ AMPHORA BLACK CAVENDISH,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
507,ΚΑΠΝΟΣ MAC BAREN MIXTURE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
508,ΚΑΠΝΟΣ MAC BAREN CLASSIC LOOSE CUT,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
509,ΠΟΥΡΑ ROMEO & JULIETA No1 A/T 3CP,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
510,ΠOYPA PARTAGAS MINI 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
511,ΠOYPA GUANTANAMERA DECIMOS 5s (10,25),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
512,ΠOYPA GUANTANAMERA CRISTALES TUBOS 10s (30,35),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
513,ΠΟΥΡΑ GUANTANAMERA DECIMOS 10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
514,ΠΟΥΡΑ JOSE PIEDRA PETIT CAZADORES 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
515,ΠΟΥΡΑ QUINTERO FAVORITOS 5s (33,75) Τ&Τ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
516,ΠΟΥΡΑ ROMEO & JULIETA No2 A/T 3CP,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
517,MARLBORO (CELO L&M BLUE) CRAFTED GOLD 100s,10,ΤΕΜΑΧΙΟ,KOYTA
518,IQOS TRAY GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
519,ΠΟΥΡΑ PANTER SPRINT 14s (5,50),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
520,SET WTF 5s 3x10 τεμ. (75,00),1,KOYTA,KOYTA
521,ΠΟΥΡΑ C/L FILTER  10s SUMATRA - ΜΠΛΕ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
522,ΠOYPA CAPTAIN BLACK CIG/LOS RUBY 10s (3,30),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
524,ΜΗΧΑΝΗ ΣΤΡΙΦΤΟΥ METAL ROLLER,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
525,ΠΟΥΡΑ CHAZZ CIGARROS 5s(6,00),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
526,IQOS  ILUMA KIT i  PRIME - ASPEN GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
527,ΦΙΛΤΡΑ DISCOVERY SMOOTH 5.7mm CHARCOAL,20,ΤΕΜΑΧΙΟ,KOYTA
528,HOLDER IQOS ILUMA - WE EDITION,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
529,HOLDER IQOS ILUMA PRIME -  JADE GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
530,CHARGER IQOS ILUMA i  PRIME - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
531,CHARGER IQOS ILUMA i  PRIME - ASPEN GREEN,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
532,CHARGER IQOS ILUMA i  PRIME - GARNET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
533,HOLDER IQOS ILUMA PRIME - BRONZE TAUPE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
534,HOLDER IQOS ILUMA ONE - PEBBLE GREY,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
535,HOLDER IQOS ILUMA ONE - SUNSET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
536,IQOS  ILUMA KIT i  PRIME - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
537,MARLBORO SLIM BLUE 7MG,10,ΤΕΜΑΧΙΟ,KOYTA
538,ΠΟΥΡΑ BREAK RED FILTER 17s,10,ΤΕΜΑΧΙΟ,KOYTA
539,ΠΟΥΡΑ BREAK BLUE FILTER 17s,10,ΤΕΜΑΧΙΟ,KOYTA
540,ΠΟΥΡΑ BREAK CIG/LOS SILVER 10s (1,20),10,ΤΕΜΑΧΙΟ,KOYTA
541,IQOS RING SET (ILUMA i PRIME - PIXEL PERFECT),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
542,IQOS DOOR (ILUMA i MID - PASSIONATE PURPLE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
543,IQOS DOOR (ILUMA i MID - VIVID BLUE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
544,IQOS DOOR (ILUMA i MID - CHILL BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
545,IQOS DOOR (ILUMA i MID - GLAMOUROUS PINK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
546,IQOS DOOR (ILUMA i MID - BRIGHT ORANGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
547,IQOS SILICONE SLEEVE (ILUMA i MID - SERENE PINK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
548,IQOS SILICONE SLEEVE (ILUMA i MID - WISE VIOLET),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
549,IQOS SILICONE SLEEVE (ILUMA i MID - JOLLY ORANGE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
550,IQOS WRAP VL (ILUMA I-PRIME -ZEST YELLOW),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
551,IQOS SILICONE SLEEVE (ILUMA i ONE - BRISK BLUE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
552,IQOS SILICONE SLEEVE (ILUMA i ONE - DELICATE BLUE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
553,IQOS SILICONE SLEEVE (ILUMA i ONE SERENE PINK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
554,IQOS WRAP VL (ILUMA I-PRIME -SMOOTH-FUSCHIA),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
555,IQOS WRAP VL (ILUMA I-PRIME -VIBRANT ORANGE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
556,IQOS SILICONE SLEEVE PLUS (ILUMA i ONE - GENTLE PINK),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
557,IQOS SILICONE SLEEVE PLUS (ILUMA i ONE - YELLOW),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
558,ΠΟΥΡΑ REPOSADO COLORADO CHURCHILL 10s (40,00) T&T,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
559,ΠΟΥΡΑ REPOSADO COLORADO TORO 10s N.T. (37,00) T&T,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
560,ΠΟΥΡΑ REPOSADO MADURO TORO 10s (37,00),1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
561,ΠΟΥΡΑ REPOSADO CONNECTICUT CHURCHILL 10s (40,00) T&T,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
562,ΠΟΥΡΑ REPOSADO MADURO ROBUSTO 10s,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
563,ΠΟΥΡΑ CLUBMASTER MINI FILTER 20s WHITE (8,50),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
564,ΠOYPA TOSCANO ANTICO (14,00) Τ&Τ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
565,ΠΟΥΡΑ TOSCANO TOSCANINO 10s (11,5),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
566,ΠΟΥΡΑ TOSCANO TOSCANINO GIALO 10s (11,5),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
567,ΠΟΥΡΑ REPOSADO COLORADO ROBUSTO 10s (33,00) Τ&Τ,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
568,ΠΟΥΡΑ PRINCIPES CORONA ORIGINAL 25s (45,00) T&T,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
569,ΠΟΥΡΑ PRINCIPES CORONA ORIGINAL5s (9,00),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
570,IQOS  ILUMA KIT i  PRIME - GARNET RED,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
571,IQOS RING SET (ILUMA i PRIME - SHIMMERING SHADES),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
572,IQOS SILICONE SLEEVE (ILUMA i ONE - MAJESTIC PURPLE),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
573,TEREA TURQUOISE,10,ΤΕΜΑΧΙΟ,KOYTA
574,TEREA TEAK,10,ΤΕΜΑΧΙΟ,KOYTA
575,HOLDER IQOS ILUMA ONE - AZURE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
576,TEREA RUSSET,10,ΤΕΜΑΧΙΟ,KOYTA
577,TEREA SIENNA,10,ΤΕΜΑΧΙΟ,KOYTA
578,ΠΟΥΡΑ VEGAFINA MINI 10s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
579,ΠΟΥΡΑ VEGAFINA CLUB 10s (6,50),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
580,TEREA AMBER,10,ΤΕΜΑΧΙΟ,KOYTA
581,TEREA SILVER,10,ΤΕΜΑΧΙΟ,KOYTA
582,TEREA KONA,10,ΤΕΜΑΧΙΟ,KOYTA
583,TEREA BRONZE,10,ΤΕΜΑΧΙΟ,KOYTA
584,ΠOYPA MONTECRISTO CLUB 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
585,ΠΟΥΡΑ PARTAGAS MINI 10s  (9,20),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
586,ΠΟΥΡΑ COHIBA WHITE MINI 20s (20,50),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
587,ΠOYPA JOSE PIEDRA CAZADORES 5s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
588,HOLDER IQOS ILUMA  - PEBBLE BEIGE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
589,TEREA YELLOW,10,ΤΕΜΑΧΙΟ,KOYTA
590,TEREA WARM FUSE,10,ΤΕΜΑΧΙΟ,KOYTA
591,ΠΟΥΡΑ ADORNADO ROBUSTO 20s San Andres,1,ΚΑΣΕΤΙΝΑ,ΚΑΣΕΤΙΝΑ
592,ZYN BLACKCURRANT FROST 11mg,1,CAN,CAN
593,LEVIA FOREST PEARL (4,20,10,ΤΕΜΑΧΙΟ,KOYTA
594,LEVIA SUMMER PEARL (4,20),10,ΤΕΜΑΧΙΟ,KOYTA
595,ΠΟΥΡΑ CLUBMASTER MINI BROWN 20s (8,00) Τ&Τ,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
596,ΠΟΥΡΑ PANTER RED FILTER 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
597,IQOS ILUMA KIT i MID - BREEZE BLUE,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
598,TEREA BEIGE,10,ΤΕΜΑΧΙΟ,KOYTA
599,ΠΟΥΡΑ HOYO DE MONTEREY No2 3s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
600,VEEV ONE BALANCED TOBACCO 1.6% (1 POD),6,ΤΕΜΑΧΙΟ,KOYTA
604,ΠOYPA COHIBA SHORT 10s (19,35),1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
605,ΠOYPA COHIBA CIGARILLOS 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
606,ΠOYPA ROMEO Y JULIETA MINI 20s,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
607,VEEV ONE BLENDED TOBACCO 1.6% (1POD),6,ΤΕΜΑΧΙΟ,KOYTA
608,ZYN SPEARMINT 9mg,1,CAN,CAN
609,ZYN PEACH 3mg,1,CAN,CAN
610,ZYN PEACH 6mg,1,CAN,CAN
611,ΚΑΠΝΟΣ PETERSON Early Morning 50g,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ
612,IQOS  ILUMA KIT i  PRIME - MIDNIGHT BLACK,1,ΤΕΜΑΧΙΟ,ΤΕΜΑΧΙΟ"""


def get_products_from_csv():
    """Parse CSV data and return list of product dictionaries"""
    products = []
    for line in PRODUCTS_CSV_DATA.strip().split('\n'):
        parts = line.split(',')
        if len(parts) == 5:
            products.append({
                "product_id": parts[0],
                "title": parts[1],
                "units_relation": int(parts[2]),
                "main_unit_description": parts[3],
                "secondary_unit_description": parts[4]
            })
    return products
